ControlTravelAgencySystem/ControlTravelAgencySystem/Models/ViewModels/RoomsView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ControlTravelAgencySystem.Models.ViewModels
{
    public class RoomsView
    {
        public class RoomViewItem
        {
            public bool IsChecked { get; set; }
            public int RoomId { get; set; }
            public string RoomNumber { get; set; }
            public int CostPerDay { get; set; }
            public string Class { get; set; }
            public int SeatsNumber { get; set; }
            public int RoomSize { get; set; }
            public string Description { get; set; }
        }

        public List<RoomViewItem> RoomViewItems { get; set; }

        public RoomsView()
        {
            RoomViewItems = new List<RoomViewItem>();
        }
    }
}

ControlTravelAgencySystem/ControlTravelAgencySystem/Models/room.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlTravelAgencySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public room()
        {
            this.callout_room = new HashSet<callout_room>();
            this.hotel_service_order = new HashSet<hotel_service_order>();
        }
    
        public int id { get; set; }
        public string number { get; set; }
        public int hotel_id { get; set; }
        public int cost_per_day { get; set; }
        public string type { get; set; }
        public int seats_number { get; set; }
        public Nullable<int> room_size { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<callout_room> callout_room { get; set; }
        public virtual hotel hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hotel_service_order> hotel_service_order { get; set; }
    }
}

ControlTravelAgencySystem/ControlTravelAgencySystem/Controllers/RoomsController.cs
using ControlTravelAgencySystem.Common;
using ControlTravelAgencySystem.Models;
using ControlTravelAgencySystem.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ControlTravelAgencySystem.Controllers
{
    /// <summary>
    /// Контроллер номеров
    /// </summary>
    public class RoomsController : Controller
    {
        // Хранилище данных БД
        private readonly TravelSystemEntities _dbContext;

        /// <summary>
        /// Инициализация
        /// </summary>
        public RoomsController(TravelSystemEntities dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpPost]
        public JsonResult RoomChecked(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return Json("fail");

            var parId = int.Parse(id);

            if (Session["selected-check"] == null)
                Session["selected-check"] = new List<int>();

            var list = Session["selected-check"] as List<int>;

            if (list.Any(x => x == parId))
            {
                list.Remove(parId);
            }
            else
            {
                list.Add(parId);
            }

            return Json("ok");
        }

        [HttpPost]
        public JsonResult FlightChecked(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return Json("fail");

            var parId = int.Parse(id);

            if (Session["flight-check"] == null)
                Session["flight-check"] = new List<int>();

            var list = Session["flight-check"] as List<int>;

            if (list.Any(x => x == parId))
                list.Remove(parId);
            else
                list.Add(parId);

            return Json("ok");
        }

        [HttpPost]
        public JsonResult RouteChecked(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return Json("fail");

            var parId = int.Parse(id);

            if (Session["route-check"] == null)
                Session["route-check"] = new List<int>();

            var list = Session["route-check"] as List<int>;

            if (list.Any(x => x == parId))
                list.Remove(parId);
            else
                list.Add(parId);

            return Json("ok");
        }

        [HttpPost]
        public JsonResult ExcursionChecked(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return Json("fail");

            var parId = int.Parse(id);

            if (Session["excursion-check"] == null)
                Session["excursion-check"] = new List<int>();

            var list = Session["excursion-check"] as List<int>;

            if (list.Any(x => x == parId))
                list.Remove(parId);
            else
                list.Add(parId);

            return Json("ok");
        }

        [HttpPost]
        public JsonResult HotelServiceChecked(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return Json("fail");

            var parId = int.Parse(id);

            if (Session["hotelservice-check"] == null)
                Session["hotelservice-check"] = new List<int>();

            var list = Session["hotelservice-check"] as List<int>;

            if (list.Any(x => x == parId))
                list.Remove(parId);
            else
                list.Add(parId);

            return Json("ok");
        }

        /// <summary>
        /// GET: /
        /// </summary>
        public ActionResult FavoriteList()
        {
            var list = Session["selected-check"] as List<int>;
            var list2 = Session["flight-check"] as List<int>;

            var viewModel = new FavotiteListView();

            if (list == null || list?.Count == 0)
                return Redirect("/Home/Index");

            foreach (var rId in list)
            {
                var room = _dbContext.rooms
                    .First(x => x.id == rId);

                var city = room.hotel.city;

                var flights = _dbContext.flights
                    .Include("airport")
                    .Where(x => x.airport1.city_id == city.id)
                    .ToList();

                var flightsList = new List<FavotiteListView.FavotiteListViewItem.FlightsItem>();

                foreach (var flight in flights)
                {
                    var isChecked = false;

                    // переписать говнокод
                    if (list2 != null)
                        if (list2.Any(x => x == flight.id))
                            isChecked = true;

                    DateTime? flightAt = null;

                    if (flight != null)
                        flightAt = Utils.tsToDateTime(flight.flight_at);

                    flightsList.Add(new FavotiteListView.FavotiteListViewItem.FlightsItem
                    {
                        IsChecked = isChecked,
                        FlightId = flight?.id,
                        Code = flight?.code,
                        FromAirport = flight?.airport,
                        ToAirport = flight?.airport1,
                        FlightAt = flightAt,
                        Duration = flight?.duration,
                        AirlineName = flight?.airline.name
                    });
                }

                var flightId = 0;

                if (flights.Count > 0)
                    flightId = flights[0].id;

                viewModel.FavotiteListViewItems.Add(new FavotiteListView.FavotiteListViewItem
                {
                    SelectedRoom = room,
                    FlightId = flightId,
                    FlightsItems = flightsList
                });
            }

            return View(viewModel);
        }

        public PartialViewResult GetRoutesList(int id)
        {
            var viewModel = new RoutesView();

            var routes = _dbContext.routes
                .Include("airport1");

            var list = Session["route-check"] as List<int>;

            foreach (var route in routes)
            {
                var isChecked = false;

                // переписать говнокод
                if (list != null)
                    if (list.Any(x => x == route.id))
                        isChecked = true;

                viewModel.RoutesViewItems.Add(
                    new RoutesView.RoutesViewItem
                    {
                        IsChecked = isChecked,
                        RouteId = route.id,
                        Type = route.type,
                        FromAirport = route.airport?.name,
                        ToAirport = route.airport1?.name,
                        StartingAddress = route.starting_address,
                        StartingTime = route.starting_time,
                        FinalAddress = route.final_address,
                        Duration = route.duration,
                        TotalSeats = route.total_seats,
                        Distance = route.distance ?? 0,
                        Cost = route.cost
                    });
            }

            return PartialView(viewModel);
        }

        public PartialViewResult GetExcursionsList(int id)
        {
            var viewModel = new ExcursionsView();

            var excursions = _dbContext.excursions
                .Where(x => x.city_id == id);

            var list = Session["excursion-check"] as List<int>;

            foreach (var excursion in excursions)
            {
                var isChecked = false;

                // переписать говнокод
                if (list != null)
                    if (list.Any(x => x == excursion.id))
                        isChecked = true;

                viewModel.ExcursionsViewItems.Add(
                    new ExcursionsView.ExcursionsViewItem
                    {
                        IsChecked = isChecked,
                        ExcursionId = excursion.id,
                        Name = excursion.name,
                        Description = excursion.description,
                        Duration = excursion.duration
                    });
            }

            return PartialView(viewModel);
        }

        public PartialViewResult GetHotelServicesList(int id)
        {
            var viewModel = new HotelServicesView();

            var hotelservices = _dbContext.hotel_service
                .Where(x => x.hotel_id == id);

            var list = Session["hotelservice-check"] as List<int>;

            foreach (var hotelservice in hotelservices)
            {
                var isChecked = false;

                // переписать говнокод
                if (list != null)
                    if (list.Any(x => x == hotelservice.id))
                        isChecked = true;

                viewModel.HotelServicesViewItems.Add(
                    new HotelServicesView.HotelServicesViewItem
                    {
                        IsChecked = isChecked,
                        HotelServiceId = hotelservice.id,
                        Description = hotelservice.description,
                        CostPerMin = hotelservice.cost_per_min,
                        StartingTime = hotelservice.starting_time
                    });
            }

            return PartialView(viewModel);
        }

        /// <summary>
        /// Представление списка номеров выбранного отеля
        /// </summary>
        /// <param name="id">ID отеля</param>
        public PartialViewResult GetRoomsList(int id)
        {
            var viewModel = GetRoomsViewModel(id);
            return PartialView(viewModel);
        }

        /// <summary>
        /// Возвращает модель-представление списка номеров
        /// </summary>
        public RoomsView GetRoomsViewModel(int id)
        {
            var viewModel = new RoomsView();

            var rooms = _dbContext.rooms
                .Include("hotel")

ControlTravelAgencySystem/ControlTravelAgencySystem/Views/Rooms/CalloutCreate.cshtml
@{
    ViewBag.Title = "Успешное оформление заявки";
}

<div class="alert alert-success notification-alert">
    <strong>Поздравляем!</strong>
    <b>Ваша заявка успешно оформлена. <a href="/" class="alert-link">На главную</a></b>
</div>

ControlTravelAgencySystem/ControlTravelAgencySystem/Views/Rooms/FavoriteList.cshtml
@model ControlTravelAgencySystem.Models.ViewModels.FavotiteListView

@{
    ViewBag.Title = "Туристическое бюро";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section scripts {
    <script src="@Href("~/Scripts/FavoriteList.js")"></script>
}

<div class="alert alert-info fade in notification-alert">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <b>Внимание!</b> 
    <span class="hvr-icon-down">
        <a href="#move-list" class="alert-link">Здесь</a> вы можете выбрать удобные авиарейсы и(или) трансферные маршруты
    </span>
</div>

<form class="modal fade" id="callout-modal" tabindex="-1" role="dialog" action="/Rooms/CalloutCreate" method="post">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">
                    Оформление заявки
                    <label class="error-label bg-danger"></label>
                </h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="fullname-input" class="control-label">ФИО:</label>
                    <input type="text" class="form-control" id="fullname-input" name="Fullname">
                </div>
                <div class="form-group">
                    <label for="fullname-input" class="control-label">Электронный адрес:</label>
                    <input type="email" class="form-control" id="email-input" name="Email">
                </div>
                <div class="form-group">
                    <label for="fullname-input" class="control-label">Телефон:</label>
                    <input type="text" class="form-control" id="phone-input" name="Phone">
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Отправить</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
            </div>
        </div>
    </div>
</form>
<div id="move-list">
    @foreach (var viewItem in Model.FavotiteListViewItems)
    {
        <div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    @*<h2>Авиакомпания @viewItem.AirlineName</h2>*@
                </div>
                <div class="panel-body">
                    @*<h3>...</h3>*@
                </div>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Отель</th>
                                <th>Город</th>
                                <th>Номер</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>@viewItem.SelectedRoom.hotel.name</td>
                                <td>@viewItem.SelectedRoom.hotel.city.name</td>
                                <td>@viewItem.SelectedRoom.number</td>
                            </tr>
                            <tr>
                                <td colspan="3">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>Выбрать</th>
                                                <th>Код</th>
                                                <th>Авиакомпания</th>
                                                <th>Город вылета</th>
                                                <th>Аэропорт вылета</th>
                                                <th>Город прилета</th>
                                                <th>Аэропорт прилета</th>
                                                <th>Дата и время отправления</th>
                                                <th>Продолжительность</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var flightItem in viewItem.FlightsItems)
                                            {
                                                <tr>
                                                    <td>
                                                        <div class="checkbox">
                                                            <input type="checkbox" class="flight-checkbox" checked="@flightItem.IsChecked" value="@flightItem.FlightId" id="flight-@(flightItem.FlightId)-checkbox" />
                                                            <label for="flight-@(flightItem.FlightId)-checkbox"></label>
                                                        </div>
                                                    </td>
                                                    <td>
                                                        @flightItem.Code
                                                    </td>
                                                    <td>
                                                        @flightItem.AirlineName
                                                    </td>
                                                    <td>
                                                        @flightItem.FromAirport.city.name
                                                    </td>
                                                    <td>
                                                        @flightItem.FromAirport.name
                                                    </td>
                                                    <td>
                                                        @flightItem.ToAirport.city.name
                                                    </td>
                                                    <td>
                                                        @flightItem.ToAirport.name
                                                    </td>
                                                    <td>
                                                        @flightItem.FlightAt
                                                    </td>
                                                    <td>
                                                        @flightItem.Duration ч.
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="8">
                                    <div id="routs-table-@viewItem.FlightId" class="routs-table">
                                        @Html.Action("GetRoutesList", "Rooms", new { id = viewItem.FlightId })
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="8">
                                    <div id="excursions-table-@viewItem.SelectedRoom.hotel.city.id" class="excursions-table">
                                        @Html.Action("GetExcursionsList", "Rooms", new { id = viewItem.SelectedRoom.hotel.city.id })
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="8">
                                    <div id="hotelservices-table-@viewItem.SelectedRoom.hotel.id" class="hotelservices-table">
                                        @Html.Action("GetHotelServicesList", "Rooms", new { id = viewItem.SelectedRoom.hotel.id })
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    }
</div>
    <script>
        $(".routs-table").fadeOut();

        $(":checkbox.flight-checkbox").change(function () {
            if (this.checked) {
                $("#routs-table-" + $(this).val()).fadeIn();
            } else {
                $("#routs-table-" + $(this).val()).fadeOut();
            }
        });
    </script>

    <script>
            $(function() {
                $(':checkbox.flight-checkbox').change(function () {
                    var id = $(this).val();
                    $.ajax({
                        url: '/rooms/flightchecked/' + id,
                        type: 'POST',
                        success: function(response) {
                            // успех
                        }
                    });
                });
                $(':checkbox.route-checkbox').change(function () {
                    var id = $(this).val();
                    $.ajax({
                        url: '/rooms/routechecked/' + id,
                        type: 'POST',
                        success: function (response) {
                            // успех
                        }
                    });
                });
                $(':checkbox.excursion-checkbox').change(function () {
                    
                    var id = $(this).val();
                    $.ajax({
                        url: '/rooms/excursionchecked/' + id,
                        type: 'POST',
                        success: function (response) {
                            // успех
                        }                    
                    });                    
                });
                $(':checkbox.hotelservice-checkbox').change(function () {

                    var id = $(this).val();
                    $.ajax({
                        url: '/rooms/hotelservicechecked/' + id,
                        type: 'POST',
                        success: function (response) {
                            // успех
                        }
                    });
                });
            });
    </script>

ControlTravelAgencySystem/ControlTravelAgencySystem/Views/Rooms/GetExcursionsList.cshtml
@model ControlTravelAgencySystem.Models.ViewModels.ExcursionsView

<div class="panel panel-default">
    <div class="panel-heading">
        <h2>Выберите экскурсию(-и)</h2>
    </div>
    <div class="panel-body">
        <h3>Список доступных экскурсий</h3>
    </div>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Добавить</th>
                    <th>Наименование</th>
                    <th>Описание</th>
                    <th>Продолжительность</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var viewItem in Model.ExcursionsViewItems)
                {
                    <tr>
                        <td>
                            <div class="checkbox">
                                <input type="checkbox" class="excursion-checkbox" checked="@viewItem.IsChecked" value="@viewItem.ExcursionId" id="excursion-@(viewItem.ExcursionId)-checkbox" />
                                <label for="excursion-@(viewItem.ExcursionId)-checkbox"></label>
                            </div>
                        </td>
                        <td>
                            @viewItem.Name
                        </td>
                        <td>
                            @viewItem.Description
                        </td>
                        <td>
                            @viewItem.Duration ч.
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

ControlTravelAgencySystem/ControlTravelAgencySystem/Views/Rooms/GetHotelServicesList.cshtml
@model ControlTravelAgencySystem.Models.ViewModels.HotelServicesView

<div class="panel panel-default">
    <div class="panel-heading">
        <h2>Выберите дополнительную услугу(-и)</h2>
    </div>
    <div class="panel-body">
        <h3>Список дополнительных услуг</h3>
    </div>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Добавить</th>                    
                    <th>Описание</th>
                    <th>Стоимость за минуту</th>
                    <th>Начало</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var viewItem in Model.HotelServicesViewItems)
                {
                    <tr>
                        <td>
                            <div class="checkbox">
                                <input type="checkbox" class="hotelservice-checkbox" checked="@viewItem.IsChecked" value="@viewItem.HotelServiceId" id="hotelservice-@(viewItem.HotelServiceId)-checkbox" />
                                <label for="hotelservice-@(viewItem.HotelServiceId)-checkbox"></label>
                            </div>
                        </td>
                        <td>
                            @viewItem.Description
                        </td>
                        <td>
                            @viewItem.CostPerMin руб.
                        </td>
                        <td>
                            @viewItem.StartingTime
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

ControlTravelAgencySystem/ControlTravelAgencySystem/Views/Rooms/GetRoomsList.cshtml
@model ControlTravelAgencySystem.Models.ViewModels.RoomsView
@using (Html.BeginForm("Check", "HotelRooms", FormMethod.Post))
{

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>Выберите комнату(-ы)</h2>
        </div>
        <div class="panel-body">
            <h3>Список номеров отеля</h3>
        </div>

        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Добавить</th>
                        <th>Номер</th>
                        <th>Стоимость проживания в сутки</th>
                        <th>Класс</th>
                        <th>Кол-во комнат</th>
                        <th>Кол-во спальных мест</th>
                        <th>Площадь</th>
                        <th>Описание</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var viewItem in Model.RoomViewItems)
                    {
                        <tr>
                            <td>
                                <div class="checkbox">
                                    <input type="checkbox" checked="@viewItem.IsChecked" value="@viewItem.RoomId" id="room-@viewItem.RoomId-checkbox"/>
                                    <label for="room-@viewItem.RoomId-checkbox"></label>
                                </div>
                            </td>
                            <td>
                                @viewItem.RoomNumber
                            </td>
                            <td>
                                @viewItem.CostPerDay руб
                            </td>
                            <td>
                                @viewItem.Class
                            </td>
                            <td>
                                @viewItem.SeatsNumber
                            </td>
                            <td>
                                @viewItem.SeatsNumber
                            </td>
                            <td>
                                @viewItem.RoomSize м²
                            </td>
                            <td>
                                @viewItem.Description
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}

<script>
    $(function() {
        $(':checkbox').change(function () {                
            var id = $(this).val();
            $.ajax({
                url: '/rooms/roomchecked/' + id,
                type: 'POST',
                success: function(response) {
                    // успех
                }
            });
        });
    });
</script>

ControlTravelAgencySystem/ControlTravelAgencySystem/Views/Rooms/GetRouteList.cshtml
@model ControlTravelAgencySystem.Models.ViewModels.RouteView
<table class="table">
    <thead>
        <tr>
            <th>Добавить</th>
            <th>Тип</th>
            <th>Из аэропорта</th>
            <th>В аэропорт</th>
            <th>Адрес отправления</th>
            <th>Время отправления</th>
            <th>Адрес прибытия</th>
            <th>Продолжительность</th>
            <th>Всего мест</th>
            <th>Расстояние</th>
            <th>Стоимость</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var viewItem in Model.RouteViewItems)
            {
            <tr>
                <td>
                    <input type="checkbox" checked="@viewItem.IsChecked" value="@viewItem.RouteId" />
                </td>
                <td>
                    @viewItem.Type
                </td>
                <td>
                    @viewItem.FromAirport
                </td>
                <td>
                    @viewItem.ToAirport
                </td>
                <td>
                    @viewItem.StartingAddress
                </td>
                <td>
                    @viewItem.StartingTime
                </td>
                <td>
                    @viewItem.FinalAddress
                </td>
                <td>
                    @viewItem.Duration ч.
                </td>
                <td>
                    @viewItem.TotalSeats
                </td>
                <td>
                    @viewItem.Distance км
                </td>
                <td>
                    @viewItem.Cost руб.
                </td>
            </tr>
        }
    </tbody>
</table>